name: Linting

on:
  push:
  pull_request:

jobs:
  PyLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pylint

      - name: Lint - PyLint
        run: |
          python -m pip install -r requirements.txt
          pylint --reports=y --fail-under=9 orphan_detection 

  Flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install flake8
      - name: Lint - Flake8
        run: |
          python -m pip install -r requirements.txt
          flake8 orphan_detection